language: python
dist: bionic
matrix:
  include:
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: 3.10
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install --upgrade setuptools
  - pip install ".[dev]"
  - pip install coverage coveralls
script:
  - pytest tests/regression_test.py
  - pytest -Werror --cov-branch --cov=mf2 tests/property_test.py tests/multi_fidelity_function_test.py
after_success:
  - coveralls
