language: python
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
install:
  - pip install .
  - pip install -U -r requirements-dev.txt
  - pip install coverage coveralls
script:
  - pytest tests/regression_test.py
  - pytest --cov=mf2 tests/property_test.py tests/multiFidelityFunction_test.py
after_success:
  - coveralls
